inherit: 
    - models/standard.yaml
    - wandb.yaml

model:
    n_dims: 20
    n_positions: 101

training:
    data: sparse_recovery
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 101
    keep_every_steps: 101
    train_steps: 101
    curriculum:
        dims:
            start: 20
            end: 20
            inc: 0
            interval: 2000